/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl;

import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Frtieptuc extends javax.swing.JFrame {

    /**
     * Creates new form Frtieptuc
     */
    public Frtieptuc() {
        initComponents();
    }

    public Frtieptuc(String a, String b, String c, String d, String cccd, String ht, String sdt) {
        initComponents();
        txtsbdi.setText(a);
        txtsbden.setText(b);
        txtngaybay.setText(c);
        txttgbay.setText(d);
        txthoten.setText(ht);
        txtccd.setText(cccd);
        txtsdt.setText(sdt);
    }

    public void upsoghe(String a) {
        txtsoghe.setText(a);
        for (int i = 0; i < 10; i++) {
            if (txtsoghe.getText().equals("A" + i)) {
                txthangghe.setText("Hạng A");
                txtgiave.setText("100000");
                txtthue.setText("10000");
                txttongtien.setText("110000");
            } else if (txtsoghe.getText().equals("B" + i)) {
                txthangghe.setText("Hạng B");
                txtgiave.setText("200000");
                txtthue.setText("20000");
                txttongtien.setText("220000");
            } else if (txtsoghe.getText().equals("C" + i)) {
                txthangghe.setText("Hạng C");
                txtgiave.setText("300000");
                txtthue.setText("30000");
                txttongtien.setText("330000");
            } else if (txtsoghe.getText().equals("D" + i)) {
                txthangghe.setText("Hạng D");
                txtgiave.setText("400000");
                txtthue.setText("40000");
                txttongtien.setText("440000");
            } else if (txtsoghe.getText().equals("E" + i)) {
                txthangghe.setText("Hạng E");
                txtgiave.setText("500000");
                txtthue.setText("50000");
                txttongtien.setText("550000");
            } else if (txtsoghe.getText().equals("F" + i)) {
                txthangghe.setText("Hạng F");
                txtgiave.setText("500000");
                txtthue.setText("50000");
                txttongtien.setText("550000");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHoso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsbdi = new javax.swing.JTextField();
        txtsoghe = new javax.swing.JTextField();
        btXacNhan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txttgbay = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtsbden = new javax.swing.JTextField();
        txtngaybay = new javax.swing.JTextField();
        txthangghe = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttongtien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtthue = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtgiave = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtccd = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btDong = new javax.swing.JButton();
        btchon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelHoso.setBackground(new java.awt.Color(221, 213, 213));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/tinhthanh.png"))); // NOI18N
        jLabel2.setText("Sân Bay Đi:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/soghe.png"))); // NOI18N
        jLabel3.setText("Số Ghế:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/masb.png"))); // NOI18N
        jLabel4.setText("Sân Bay Đến:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/date.png"))); // NOI18N
        jLabel5.setText("Ngày Bay:");

        txtsbdi.setMinimumSize(new java.awt.Dimension(64, 26));
        txtsbdi.setPreferredSize(new java.awt.Dimension(64, 25));

        txtsoghe.setEditable(false);
        txtsoghe.setMinimumSize(new java.awt.Dimension(64, 26));
        txtsoghe.setPreferredSize(new java.awt.Dimension(64, 25));

        btXacNhan.setBackground(new java.awt.Color(51, 153, 0));
        btXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/dautich.png"))); // NOI18N
        btXacNhan.setText("Xác Nhận");
        btXacNhan.setPreferredSize(new java.awt.Dimension(119, 39));
        btXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacNhanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/time.png"))); // NOI18N
        jLabel8.setText("Thời Gian Bay:");

        txttgbay.setMinimumSize(new java.awt.Dimension(64, 26));
        txttgbay.setPreferredSize(new java.awt.Dimension(64, 25));

        jPanel10.setBackground(new java.awt.Color(251, 195, 138));

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/airline.png"))); // NOI18N
        jLabel6.setText("THÔNG TIN VÉ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtsbden.setMinimumSize(new java.awt.Dimension(64, 26));
        txtsbden.setPreferredSize(new java.awt.Dimension(64, 25));
        txtsbden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsbdenActionPerformed(evt);
            }
        });

        txtngaybay.setMinimumSize(new java.awt.Dimension(64, 26));
        txtngaybay.setPreferredSize(new java.awt.Dimension(64, 25));
        txtngaybay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaybayActionPerformed(evt);
            }
        });

        txthangghe.setEditable(false);
        txthangghe.setMinimumSize(new java.awt.Dimension(64, 26));
        txthangghe.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/iconUser.png"))); // NOI18N
        jLabel7.setText("Hạng Ghế:");

        txttongtien.setEditable(false);
        txttongtien.setMinimumSize(new java.awt.Dimension(64, 26));
        txttongtien.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/tongtien.png"))); // NOI18N
        jLabel9.setText("Tổng Tiền:");

        txtthue.setEditable(false);
        txtthue.setMinimumSize(new java.awt.Dimension(64, 26));
        txtthue.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/thue.png"))); // NOI18N
        jLabel10.setText("Thuế:");

        txtgiave.setEditable(false);
        txtgiave.setMinimumSize(new java.awt.Dimension(64, 26));
        txtgiave.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/giave.png"))); // NOI18N
        jLabel11.setText("Giá Vé:");

        txtsdt.setMinimumSize(new java.awt.Dimension(64, 26));
        txtsdt.setPreferredSize(new java.awt.Dimension(64, 25));
        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/sdt.png"))); // NOI18N
        jLabel12.setText("Số Điện Thoại:");

        txthoten.setMinimumSize(new java.awt.Dimension(64, 26));
        txthoten.setPreferredSize(new java.awt.Dimension(64, 25));
        txthoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthotenActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/hoten.png"))); // NOI18N
        jLabel13.setText("Họ Và Tên:");

        txtccd.setMinimumSize(new java.awt.Dimension(64, 26));
        txtccd.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/makh.png"))); // NOI18N
        jLabel14.setText("CCCD:");

        btDong.setBackground(new java.awt.Color(204, 51, 0));
        btDong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btDong.setForeground(new java.awt.Color(255, 255, 255));
        btDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/daux.png"))); // NOI18N
        btDong.setText("Đóng >>");
        btDong.setPreferredSize(new java.awt.Dimension(119, 39));
        btDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDongActionPerformed(evt);
            }
        });

        btchon.setBackground(new java.awt.Color(153, 153, 255));
        btchon.setText("Chọn");
        btchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHosoLayout = new javax.swing.GroupLayout(jPanelHoso);
        jPanelHoso.setLayout(jPanelHosoLayout);
        jPanelHosoLayout.setHorizontalGroup(
            jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHosoLayout.createSequentialGroup()
                .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHosoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelHosoLayout.createSequentialGroup()
                                .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addComponent(jLabel2)))
                                .addGap(53, 53, 53)
                                .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsbdi, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttgbay, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsbden, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtngaybay, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelHosoLayout.createSequentialGroup()
                                .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(12, 12, 12)
                                .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txthangghe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelHosoLayout.createSequentialGroup()
                                        .addComponent(btchon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addComponent(txtsoghe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHosoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelHosoLayout.createSequentialGroup()
                            .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(53, 53, 53)
                            .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtccd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtgiave, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelHosoLayout.createSequentialGroup()
                            .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))
                            .addGap(53, 53, 53)
                            .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtthue, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelHosoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btDong, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(189, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelHosoLayout.setVerticalGroup(
            jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHosoLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHosoLayout.createSequentialGroup()
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtsbdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtsbden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtngaybay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txttgbay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtsoghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btchon))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txthangghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelHosoLayout.createSequentialGroup()
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtgiave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtthue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelHoso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelHoso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXacNhanActionPerformed
        // TODO add your handling code here:
        KetNoi kn = new KetNoi();
        int op = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đặt vé không ?", "THÔNG BÁO", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Bạn đã đặt vé thành công");
            JOptionPane.showMessageDialog(this, "Chúc bạn một ngày tốt lành!");
            String mave = null;
            try {
                ResultSet kq = kn.laymave();
                if (kq != null) {
                    int maxIndex = 0;
                    while (kq.next()) {
                        String gt = kq.getString("mave");
                        int index = Integer.parseInt(gt.substring(2)); // Lấy phần số của mã vé
                        if (index > maxIndex) {
                            maxIndex = index;
                        }
                    }
                    System.out.println(maxIndex);
                    mave = "VE"+(maxIndex+1);
                }
            } catch (Exception e) {
                System.out.println("Lỗi" + e.toString());
            }
            String hoten = txthoten.getText();
            String cccd = txtccd.getText();
            String sbdi = txtsbdi.getText();
            String sbden = txtsbden.getText();
            String macb = kn.getmacb(sbdi, sbden);
            String soghe = txtsoghe.getText();
            String hangghe = txthangghe.getText();
            double thue = Double.parseDouble(txtthue.getText());
            double giave = Double.parseDouble(txtgiave.getText());
            double tongtien = Double.parseDouble(txttongtien.getText());
            String trangthai = "Chưa thanh toán";
            try {
                kn.themvct(mave, hoten, cccd, macb, soghe, hangghe, giave, thue, tongtien, trangthai);

            } catch (Exception e) {
                System.out.println("Loi" + e.getMessage());
            }
            this.setVisible(false);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_btXacNhanActionPerformed

    private void txtsbdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsbdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsbdenActionPerformed

    private void txtngaybayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaybayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaybayActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void txthotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthotenActionPerformed

    private void btDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDongActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn đóng không ?", "THÔNG BÁO", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_btDongActionPerformed

    private void btchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchonActionPerformed
        // TODO add your handling code here:
        Frchonghe formChonGhe = new Frchonghe(Frtieptuc.this);
        formChonGhe.setVisible(true);
    }//GEN-LAST:event_btchonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frtieptuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frtieptuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frtieptuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frtieptuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frtieptuc().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDong;
    private javax.swing.JButton btXacNhan;
    private javax.swing.JButton btchon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanelHoso;
    private javax.swing.JTextField txtccd;
    private javax.swing.JTextField txtgiave;
    private javax.swing.JTextField txthangghe;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtngaybay;
    private javax.swing.JTextField txtsbden;
    private javax.swing.JTextField txtsbdi;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtsoghe;
    private javax.swing.JTextField txttgbay;
    private javax.swing.JTextField txtthue;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables

}
