/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MenuUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     */
    public MenuUser() {
        initComponents();
        hienthihoso();

    }
    KetNoi db = new KetNoi();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanelDatVe = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbDatve = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        cbbdiemkhoihanh = new javax.swing.JComboBox<>();
        cbbdiemdendv = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        btxem = new javax.swing.JButton();
        bttimkiemve = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        datengaybay = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        jPanelVecuatoi = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbvecuatoi = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        btthanhtoan = new javax.swing.JButton();
        btHuy = new javax.swing.JButton();
        jPanelHoso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txthotenkh = new javax.swing.JTextField();
        bttaomoi = new javax.swing.JButton();
        btluu = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcccd = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboboxgt = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(135, 206, 235));
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/logout.png"))); // NOI18N
        jButton1.setText("Đăng Xuất");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/home.png"))); // NOI18N
        jButton2.setText("Trang Chủ");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/hoso.png"))); // NOI18N
        jButton5.setText("Hồ Sơ");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/ve.png"))); // NOI18N
        jButton3.setText("Đặt Vé");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/plane-ticket.png"))); // NOI18N
        jButton4.setText("Vé Của Tôi");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/Gif trangchu.gif"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/datve.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(540, 540, 540))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", jPanel2);

        jPanelDatVe.setBackground(new java.awt.Color(221, 213, 213));

        tbDatve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Chuyến Bay", "Ngày Cất Cánh", "Thời Gian Đi", "Sân Bay Đi", "Sân Bay Đến"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    tbDatve.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    tbDatve.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tbDatveMouseClicked(evt);
        }
    });
    jScrollPane5.setViewportView(tbDatve);

    jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/tensb.png"))); // NOI18N
    jLabel33.setText("ĐIỂM KHỞI HÀNH");

    jPanel17.setBackground(new java.awt.Color(251, 195, 138));

    jLabel36.setBackground(new java.awt.Color(255, 255, 0));
    jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel36.setForeground(new java.awt.Color(255, 255, 255));
    jLabel36.setText("ĐẶT VÉ");

    javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
    jPanel17.setLayout(jPanel17Layout);
    jPanel17Layout.setHorizontalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addGap(560, 560, 560)
            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(638, Short.MAX_VALUE))
    );
    jPanel17Layout.setVerticalGroup(
        jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel17Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(9, Short.MAX_VALUE))
    );

    cbbdiemkhoihanh.setBackground(new java.awt.Color(153, 153, 0));
    cbbdiemkhoihanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    cbbdiemkhoihanh.setPreferredSize(new java.awt.Dimension(98, 35));

    cbbdiemdendv.setBackground(new java.awt.Color(153, 153, 0));
    cbbdiemdendv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    cbbdiemdendv.setPreferredSize(new java.awt.Dimension(98, 35));

    jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/date.png"))); // NOI18N
    jLabel37.setText("NGÀY BAY");

    btxem.setBackground(new java.awt.Color(102, 0, 102));
    btxem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btxem.setForeground(new java.awt.Color(255, 255, 255));
    btxem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/timkiem.png"))); // NOI18N
    btxem.setText("Xem");
    btxem.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btxemActionPerformed(evt);
        }
    });

    bttimkiemve.setBackground(new java.awt.Color(102, 0, 102));
    bttimkiemve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    bttimkiemve.setForeground(new java.awt.Color(255, 255, 255));
    bttimkiemve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/timkiem.png"))); // NOI18N
    bttimkiemve.setText("Tìm Kiếm");
    bttimkiemve.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bttimkiemveActionPerformed(evt);
        }
    });

    jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/masb.png"))); // NOI18N
    jLabel38.setText("ĐIỂM ĐẾN");

    datengaybay.setDateFormatString("yyyy,MM,dd");

    jPanel1.setBackground(new java.awt.Color(221, 213, 213));

    jButton32.setBackground(new java.awt.Color(102, 0, 102));
    jButton32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jButton32.setForeground(new java.awt.Color(255, 255, 255));
    jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/timkiem.png"))); // NOI18N
    jButton32.setText("Tiếp Tục");
    jButton32.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton32ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton32)
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jButton32)
            .addGap(0, 14, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanelDatVeLayout = new javax.swing.GroupLayout(jPanelDatVe);
    jPanelDatVe.setLayout(jPanelDatVeLayout);
    jPanelDatVeLayout.setHorizontalGroup(
        jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanelDatVeLayout.createSequentialGroup()
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1293, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(jPanelDatVeLayout.createSequentialGroup()
            .addGroup(jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDatVeLayout.createSequentialGroup()
                    .addGap(241, 241, 241)
                    .addGroup(jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel33)
                        .addComponent(cbbdiemkhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatVeLayout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(cbbdiemdendv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(76, 76, 76)
                            .addComponent(bttimkiemve))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatVeLayout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jLabel38)))
                    .addGroup(jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDatVeLayout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(datengaybay, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(btxem))
                        .addGroup(jPanelDatVeLayout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(jLabel37))))
                .addGroup(jPanelDatVeLayout.createSequentialGroup()
                    .addGap(577, 577, 577)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(185, Short.MAX_VALUE))
    );
    jPanelDatVeLayout.setVerticalGroup(
        jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelDatVeLayout.createSequentialGroup()
            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelDatVeLayout.createSequentialGroup()
                    .addGroup(jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel33)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDatVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbdiemdendv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbdiemkhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(bttimkiemve)))
                .addGroup(jPanelDatVeLayout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(datengaybay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(btxem, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(95, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("tab9", jPanelDatVe);

    jPanelVecuatoi.setBackground(new java.awt.Color(221, 213, 213));

    tbvecuatoi.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null, null, null},
            {null, null, null, null, null, null, null, null, null, null}
        },
        new String [] {
            "Mã Vé", "Họ Tên", "CCCD", "Mã Chuyến Bay", "Số Ghế", "Hạng Ghế", "Giá Vé", "Thuế", "Tổng Tiền", "Trạng Thái"
        }
    )
    {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }
    );
    tbvecuatoi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane4.setViewportView(tbvecuatoi);
    if (tbvecuatoi.getColumnModel().getColumnCount() > 0) {
        tbvecuatoi.getColumnModel().getColumn(0).setMinWidth(50);
        tbvecuatoi.getColumnModel().getColumn(0).setMaxWidth(50);
        tbvecuatoi.getColumnModel().getColumn(1).setMinWidth(150);
        tbvecuatoi.getColumnModel().getColumn(1).setMaxWidth(150);
        tbvecuatoi.getColumnModel().getColumn(2).setMinWidth(120);
        tbvecuatoi.getColumnModel().getColumn(2).setMaxWidth(120);
        tbvecuatoi.getColumnModel().getColumn(3).setMinWidth(120);
        tbvecuatoi.getColumnModel().getColumn(3).setMaxWidth(120);
        tbvecuatoi.getColumnModel().getColumn(4).setMinWidth(100);
        tbvecuatoi.getColumnModel().getColumn(4).setMaxWidth(100);
        tbvecuatoi.getColumnModel().getColumn(5).setMinWidth(100);
        tbvecuatoi.getColumnModel().getColumn(5).setMaxWidth(100);
        tbvecuatoi.getColumnModel().getColumn(6).setMinWidth(120);
        tbvecuatoi.getColumnModel().getColumn(6).setMaxWidth(120);
        tbvecuatoi.getColumnModel().getColumn(7).setMinWidth(120);
        tbvecuatoi.getColumnModel().getColumn(7).setMaxWidth(120);
        tbvecuatoi.getColumnModel().getColumn(8).setMinWidth(120);
        tbvecuatoi.getColumnModel().getColumn(8).setMaxWidth(120);
    }

    jPanel16.setBackground(new java.awt.Color(251, 195, 138));

    jLabel32.setBackground(new java.awt.Color(255, 255, 0));
    jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel32.setForeground(new java.awt.Color(255, 255, 255));
    jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/onggia.png"))); // NOI18N
    jLabel32.setText("VÉ CỦA TÔI");

    javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
    jPanel16.setLayout(jPanel16Layout);
    jPanel16Layout.setHorizontalGroup(
        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel16Layout.createSequentialGroup()
            .addGap(482, 482, 482)
            .addComponent(jLabel32)
            .addContainerGap(1019, Short.MAX_VALUE))
    );
    jPanel16Layout.setVerticalGroup(
        jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addContainerGap())
    );

    btthanhtoan.setBackground(new java.awt.Color(102, 0, 102));
    btthanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btthanhtoan.setForeground(new java.awt.Color(255, 255, 255));
    btthanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/macb.png"))); // NOI18N
    btthanhtoan.setText("Thanh Toán");
    btthanhtoan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btthanhtoanActionPerformed(evt);
        }
    });

    btHuy.setBackground(new java.awt.Color(204, 51, 0));
    btHuy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btHuy.setForeground(new java.awt.Color(255, 255, 255));
    btHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/daux.png"))); // NOI18N
    btHuy.setText("Hủy Vé");
    btHuy.setPreferredSize(new java.awt.Dimension(119, 39));
    btHuy.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btHuyActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanelVecuatoiLayout = new javax.swing.GroupLayout(jPanelVecuatoi);
    jPanelVecuatoi.setLayout(jPanelVecuatoiLayout);
    jPanelVecuatoiLayout.setHorizontalGroup(
        jPanelVecuatoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanelVecuatoiLayout.createSequentialGroup()
            .addGap(429, 429, 429)
            .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(47, 47, 47)
            .addComponent(btthanhtoan)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanelVecuatoiLayout.createSequentialGroup()
            .addComponent(jScrollPane4)
            .addContainerGap())
    );
    jPanelVecuatoiLayout.setVerticalGroup(
        jPanelVecuatoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelVecuatoiLayout.createSequentialGroup()
            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(29, 29, 29)
            .addGroup(jPanelVecuatoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btthanhtoan)
                .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(183, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("tab9", jPanelVecuatoi);

    jPanelHoso.setBackground(new java.awt.Color(221, 213, 213));

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/hoten.png"))); // NOI18N
    jLabel2.setText("Họ Và Tên:");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/gioitinh.png"))); // NOI18N
    jLabel4.setText("Giới Tính:");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/date.png"))); // NOI18N
    jLabel5.setText("Ngày Sinh:");

    txthotenkh.setMinimumSize(new java.awt.Dimension(64, 26));
    txthotenkh.setPreferredSize(new java.awt.Dimension(64, 25));

    bttaomoi.setBackground(new java.awt.Color(102, 0, 102));
    bttaomoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    bttaomoi.setForeground(new java.awt.Color(255, 255, 255));
    bttaomoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/refresh.png"))); // NOI18N
    bttaomoi.setText("Tạo Mới");
    bttaomoi.setPreferredSize(new java.awt.Dimension(119, 39));
    bttaomoi.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bttaomoiActionPerformed(evt);
        }
    });

    btluu.setBackground(new java.awt.Color(255, 193, 7));
    btluu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btluu.setForeground(new java.awt.Color(255, 255, 255));
    btluu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/updated.png"))); // NOI18N
    btluu.setText("Lưu");
    btluu.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btluuActionPerformed(evt);
        }
    });

    jPanel9.setBackground(new java.awt.Color(0, 102, 153));

    jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(255, 255, 255));
    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/tinhthanh.png"))); // NOI18N
    jLabel9.setText("Địa Chỉ:");

    txtdiachi.setMinimumSize(new java.awt.Dimension(64, 26));
    txtdiachi.setPreferredSize(new java.awt.Dimension(64, 25));

    jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(255, 255, 255));
    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/sdt.png"))); // NOI18N
    jLabel10.setText("Số Điện Thoại:");

    txtsdt.setMinimumSize(new java.awt.Dimension(64, 26));
    txtsdt.setPreferredSize(new java.awt.Dimension(64, 25));

    jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(255, 255, 255));
    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/hoten.png"))); // NOI18N
    jLabel11.setText("THÔNG TIN LIÊN HỆ");

    jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel12.setForeground(new java.awt.Color(255, 255, 255));
    jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/gmail.png"))); // NOI18N
    jLabel12.setText("Email:");

    txtemail.setMinimumSize(new java.awt.Dimension(64, 26));
    txtemail.setPreferredSize(new java.awt.Dimension(64, 25));

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addGap(186, 186, 186)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(53, 53, 53)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap(113, Short.MAX_VALUE))
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addComponent(jLabel11)
            .addGap(13, 13, 13)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(20, 20, 20)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(55, Short.MAX_VALUE))
    );

    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/cccd.png"))); // NOI18N
    jLabel8.setText("Số CCCD:");

    txtcccd.setMinimumSize(new java.awt.Dimension(64, 26));
    txtcccd.setPreferredSize(new java.awt.Dimension(64, 25));

    jPanel10.setBackground(new java.awt.Color(251, 195, 138));

    jLabel6.setBackground(new java.awt.Color(255, 255, 0));
    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setText("HỒ SƠ");

    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
    jPanel10.setLayout(jPanel10Layout);
    jPanel10Layout.setHorizontalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
            .addContainerGap(613, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(460, 460, 460))
    );
    jPanel10Layout.setVerticalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel10Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(9, Short.MAX_VALUE))
    );

    comboboxgt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btl/hoten.png"))); // NOI18N
    jLabel7.setText("THÔNG TIN CÁ NHÂN");

    txtngaysinh.setMinimumSize(new java.awt.Dimension(64, 26));
    txtngaysinh.setPreferredSize(new java.awt.Dimension(64, 25));

    javax.swing.GroupLayout jPanelHosoLayout = new javax.swing.GroupLayout(jPanelHoso);
    jPanelHoso.setLayout(jPanelHosoLayout);
    jPanelHosoLayout.setHorizontalGroup(
        jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelHosoLayout.createSequentialGroup()
            .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelHosoLayout.createSequentialGroup()
                    .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelHosoLayout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHosoLayout.createSequentialGroup()
                            .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelHosoLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(53, 53, 53)
                                    .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelHosoLayout.createSequentialGroup()
                                    .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addComponent(jLabel2))
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txthotenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboboxgt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(9, 9, 9)))
                    .addComponent(bttaomoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)
                    .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btluu)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanelHosoLayout.setVerticalGroup(
        jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelHosoLayout.createSequentialGroup()
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanelHosoLayout.createSequentialGroup()
                    .addComponent(jLabel7)
                    .addGap(24, 24, 24)
                    .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtcccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txthotenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(comboboxgt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(110, 110, 110)
            .addGroup(jPanelHosoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bttaomoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btluu))
            .addContainerGap(161, Short.MAX_VALUE))
    );

    jTabbedPane2.addTab("tab9", jPanelHoso);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void hienthive() {
        ResultSet kq = (ResultSet) db.laykqvct();
        if (kq != null) {
            db.loadTable((ResultSet) kq, tbvecuatoi);
        }
    }

    public void hienthihoso() {
        try {
            ResultSet kq = (ResultSet) db.layhoso();
            if (kq != null) {
                while (kq.next()) {
                    txtcccd.setText(kq.getString("cccd"));
                    txthotenkh.setText(kq.getString("hoten"));
                    txtdiachi.setText(kq.getString("diachi"));
                    txtsdt.setText(kq.getString("sdt"));
                    txtemail.setText(kq.getString("email"));
                    txtngaysinh.setText(kq.getString("ngaysinh"));
                    comboboxgt.setSelectedItem(kq.getString("gioitinh"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void hienthicbb() {
        try {
            ResultSet kq = db.laykqcbb();
            if (kq != null) {
                cbbdiemkhoihanh.removeAllItems();
                cbbdiemdendv.removeAllItems();
                while (kq.next()) {
                    String gt = kq.getString("tinhthanh");
                    cbbdiemkhoihanh.addItem(gt);
                    cbbdiemdendv.addItem(gt);
                }
            }
        } catch (Exception e) {
            System.out.println("Lỗi" + e.toString());
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(this, "Bạn có thực sự muốn Đăng Xuất không ?", "ĐĂNG XUẤT", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            Login a = new Login();
            a.show();
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(1);
        hienthicbb();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(2);
        hienthive();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane2.setSelectedIndex(3);
        hienthihoso();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bttaomoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttaomoiActionPerformed
        // TODO add your handling code here:
        txtdiachi.setText("");
        txtemail.setText("");
        txthotenkh.setText("");
        txtngaysinh.setText("");
        txtsdt.setText("");
        comboboxgt.setSelectedItem("Nam");
    }//GEN-LAST:event_bttaomoiActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbDatve.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy dữ liệu từ hàng được chọn
            String value1 = (String) tbDatve.getValueAt(selectedRow, 0);
            String value2 = (String) tbDatve.getValueAt(selectedRow, 1);
            String value3 = (String) tbDatve.getValueAt(selectedRow, 2);
            String value4 = (String) tbDatve.getValueAt(selectedRow, 3);
            String value5 = (String) tbDatve.getValueAt(selectedRow, 4);

            // Hiển thị dữ liệu lên JTextField
            Frtieptuc a = new Frtieptuc(value4, value5, value2, value3, txtcccd.getText(), txthotenkh.getText(), txtsdt.getText());
            a.show();
        }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void bttimkiemveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttimkiemveActionPerformed
        // TODO add your handling code here:
        String diemKhoiHanh = cbbdiemkhoihanh.getSelectedItem().toString().trim();
        String diemDen = cbbdiemdendv.getSelectedItem().toString().trim();
        try {
            db.timdatve(diemKhoiHanh, diemDen, tbDatve);
        } catch (SQLException ex) {
            Logger.getLogger(MenuUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttimkiemveActionPerformed

    private void btxemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxemActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngaybay = dateFormat.format(datengaybay.getDate());
        try {
            db.xemdatve(ngaybay, tbDatve);
        } catch (SQLException ex) {
            Logger.getLogger(MenuUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btxemActionPerformed

    private void btthanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthanhtoanActionPerformed
        // TODO add your handling code here:
        KetNoi kn = new KetNoi();
        String trangthai = "Đã thanh toán";
        int selectedRow = tbvecuatoi.getSelectedRow();
        if (selectedRow != -1) {
            String value1 = (String) tbvecuatoi.getValueAt(selectedRow, 0);
            String value2 = (String) tbvecuatoi.getValueAt(selectedRow, 1);
            String value3 = (String) tbvecuatoi.getValueAt(selectedRow, 2);
            String value4 = (String) tbvecuatoi.getValueAt(selectedRow, 3);
            double value9 = Double.parseDouble((String) tbvecuatoi.getValueAt(selectedRow, 8));
            String value10 = (String) tbvecuatoi.getValueAt(selectedRow, 9);
            if (value10.equals("Chưa thanh toán")) {
                try {
                    int op = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thanh toán không ?", "THÔNG BÁO", JOptionPane.YES_NO_OPTION);
                    if (op == JOptionPane.YES_OPTION) {
                        db.suavct(value1, trangthai);
                        hienthive();
                        JOptionPane.showMessageDialog(this, "Bạn đã thanh toán thành công!\n Chúc bạn một ngày tốt lành");
                        String mahd = null;
                        try {
                            ResultSet kq = kn.laymahd();
                            if (kq != null) {
                                int maxIndex = 0;
                                while (kq.next()) {
                                    String gt = kq.getString("mahd");
                                    int index = Integer.parseInt(gt.substring(2));
                                    if (index > maxIndex) {
                                        maxIndex = index;
                                    }
                                }
                                mahd = "HD"+(maxIndex+1);
                            }
                        } catch (Exception e) {
                            System.out.println("Lỗi" + e.toString());
                        }
                        kn.themhoadon(mahd, value1, value2, value3, value4, value9);
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(MenuUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Hóa Đơn này đã được thanh toán");
            }
        }
    }//GEN-LAST:event_btthanhtoanActionPerformed

    private void tbDatveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatveMouseClicked

    }//GEN-LAST:event_tbDatveMouseClicked

    private void btluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn sửa thông tin không ?", "THÔNG BÁO", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            String cccd = txtcccd.getText();
            String sdt = txtsdt.getText();
            String hoten = txthotenkh.getText();
            String ngaysinh = txtngaysinh.getText();
            String diachi = txtdiachi.getText();
            String email = txtemail.getText();
            String gioitinh = comboboxgt.getSelectedItem().toString();
            KetNoi kn = new KetNoi();
            try {
                kn.suahoso(cccd, hoten, gioitinh, ngaysinh, sdt, diachi, email);
                JOptionPane.showMessageDialog(this, "Đã sửa thông tin thành công");
                hienthihoso();
            } catch (Exception e) {
                System.out.println("Loi" + e.getMessage());
            }
        }

    }//GEN-LAST:event_btluuActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        // TODO add your handling code here:
        KetNoi kn = new KetNoi();
        int selectedRow = tbvecuatoi.getSelectedRow();
        String value10 = null;
        if (selectedRow != -1) {
            value10 = (String) tbvecuatoi.getValueAt(selectedRow, 9);
        }

        int sohang = tbvecuatoi.getSelectedRowCount();
        if (sohang == 0) {
            JOptionPane.showConfirmDialog(this, "Bạn chưa chọn để hủy");
        } else {
            if (value10.equals("Đã thanh toán")) {
                JOptionPane.showMessageDialog(this, "Vé này đã thanh toán, nên không thể hủy");
            } else {
                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn hủy không?", "Chú ý", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    int cs_hangchon = tbvecuatoi.getSelectedRow();
                    String mave = tbvecuatoi.getValueAt(cs_hangchon, 0).toString();
                    db.xoave(mave);
                    hienthive();
                    JOptionPane.showMessageDialog(this, "Đã hủy Vé thành công!");
                }
            }

        }
    }//GEN-LAST:event_btHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btluu;
    private javax.swing.JButton bttaomoi;
    private javax.swing.JButton btthanhtoan;
    private javax.swing.JButton bttimkiemve;
    private javax.swing.JButton btxem;
    private javax.swing.JComboBox<String> cbbdiemdendv;
    private javax.swing.JComboBox<String> cbbdiemkhoihanh;
    private javax.swing.JComboBox<String> comboboxgt;
    private com.toedter.calendar.JDateChooser datengaybay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDatVe;
    private javax.swing.JPanel jPanelHoso;
    private javax.swing.JPanel jPanelVecuatoi;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbDatve;
    private javax.swing.JTable tbvecuatoi;
    private javax.swing.JTextField txtcccd;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthotenkh;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
